# MediaPipe graph that performs pose estimation with TensorFlow Lite on CPU

input_stream: "input_video"  # ImageFrame
output_stream: "pose_landmarks"  # NormalizedLandmarkList

# subgraph that limits images flowing downstream to prevent back-ups
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:pose_landmarks"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# subgraph that detects poses and corresponding landmarks
node {
  calculator: "PoseLandmarkCpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "LANDMARKS:pose_landmarks"
}
