# MediaPipe graph that performs pose tracking with TensorFlow Lite on CPU.

# CPU buffer (ImageFrame).
input_stream: "input_video"

# Pose landmarks (NormalizedLandmarkList).
output_stream: "pose_landmarks"

# Subgraph that detects poses and corresponding landmarks.
node {
  calculator: "PoseLandmarkCpu"
  input_stream: "IMAGE:input_video"
  output_stream: "LANDMARKS:pose_landmarks"
}
