#include "pose.h"

const vector<string> PoseEstimator::body_parts = {
  "nose",
  "right_eye_inner",
  "right_eye",
  "right_eye_outer",
  "left_eye_inner",
  "left_eye",
  "left_eye_outer",
  "right_ear",
  "left_ear",
  "mouth_right",
  "mouth_left",
  "right_shoulder",
  "left_shoulder",
  "right_elbow",
  "left_elbow",
  "right_wrist",
  "left_wrist",
  "right_pinky",
  "left_pinky",
  "right_index",
  "left_index",
  "right_thumb",
  "left_thumb",
  "right_hip",
  "left_hip",
  "right_knee",
  "left_knee",
  "right_ankle",
  "left_ankle",
  "right_heel",
  "left_heel",
  "right_foot_index",
  "left_foot_index"
};
